services:
  db-postgres:
    image: postgres:16
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_HOST: ${DB_HOST}
        POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django-web:
    build: .
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
    volumes:
      - .:/src
    env_file:
     - .env
    command: "/bin/bash -c './manage.py migrate; python3 manage.py runserver 0.0.0.0:8000'"
    depends_on:
      - db-postgres

    ports:
      - "${DJANGO_PROJECT_PORT}:${DJANGO_PROJECT_PORT}"

volumes:
  pgdata:
