# Generated by Django 5.1.4 on 2025-01-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='answer',
        ),
        migrations.AddField(
            model_name='response',
            name='mark',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.mark'),
        ),
    ]
