# Generated by Django 5.1.4 on 2025-01-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_mark_answer_response_mark'),
        ('management', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='mark',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.mark'),
        ),
        migrations.AlterField(
            model_name='response',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='management.task'),
        ),
    ]
