# Generated by Django 5.1.4 on 2025-01-30 13:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_response_mark_alter_response_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='description',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='Description'),
        ),
    ]
