# Generated by Django 5.1.4 on 2025-02-01 17:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_response_description'),
        ('management', '0007_alter_task_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(max_length=500, verbose_name='Description')),
                ('submission_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Submission datetime')),
                ('mark', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.mark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='management.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
