# Generated by Django 5.1.4 on 2025-02-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_answer_delete_response'),
        ('management', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='management.task'),
        ),
    ]
