version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Run tests poetry
          command: poetry run python manage.py test

      - run:
          name: Run tests
          command: python manage.py test


workflows:
  build-and-test:
    jobs:
      - test-python
