version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12
      - image: postgres:16
        environment:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - python/install-packages:
          pkg-manager: poetry


      - run:
          name: Wait for PostgreSQL to be Ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 60s

      - run:
          name: Run Database Migrations
          command: |
            export DATABASE_URL=postgresql://testuser:testpassword@localhost:5432/testdb
            poetry run python manage.py migrate


      - run:
          name: Run Tests
          command: poetry run manage.py test --settings=config.settings.dev

workflows:
  build-and-test:
    jobs:
      - test-python
