version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12-node
      - image: postgres:16
        name: db-postgres
        environment:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: example
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: sleep 10
      - run:
          name: Check Database Connection
          command: |
            PGPASSWORD=example psql -h $DB_HOST -U testuser -d testdb -c "SELECT 1;"
      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Run tests
          command: poetry run python manage.py test

workflows:
  build-and-test:
    jobs:
      - test-python
