version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

workflows:
  build-and-test:
    jobs:
      - test-python
