# Generated by Django 5.1.4 on 2025-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_task_deadline_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
