# Generated by Django 5.1.4 on 2025-01-31 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 7), null=True, verbose_name='Deadline'),
        ),
    ]
