# Generated by Django 5.1.4 on 2025-02-10 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_task_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=[], related_name='courses_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
