# Generated by Django 5.1.4 on 2025-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_course_start_datetime_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_datetime',
            field=models.DateField(verbose_name='Start datetime'),
        ),
    ]
