# Generated by Django 5.1.4 on 2025-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_course_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Start datetime'),
        ),
    ]
