# Generated by Django 5.1.4 on 2025-02-11 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_course_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Tags'), default=list, size=None),
        ),
    ]
