# Generated by Django 5.1.4 on 2025-02-13 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 20), null=True, verbose_name='Deadline'),
        ),
    ]
