# Generated by Django 5.1.7 on 2025-03-20 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0021_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                blank=True,
                default=datetime.date(2025, 3, 27),
                null=True,
                verbose_name="Deadline",
            ),
        ),
    ]
