# Generated by Django 5.1.4 on 2025-02-10 17:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default-avatar.png', null=True, storage=storages.backends.s3.S3Storage(), upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
